DROP TABLE IF EXISTS result;
DROP TABLE IF EXISTS user;

CREATE TABLE result (
  filename TEXT PRIMARY KEY,
  severity INTEGER NOT NULL,
  probability INTEGER NOT NULL
);

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  firstname TEXT NOT NULL,
  lastname TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);